{% set name = "python-discovery" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: cf87d3627dfb4412437fdd5b13eae402607722998d21567993aedbc59b23c15e

build:
  number: 0
  skip: true # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatch-vcs >=0.5
    - hatchling >=1.28
    - pip
  run:
    - python
    - filelock >=3.15.4

test:
  source_files:
    - tests
  imports:
    - python_discovery
  commands:
    - pip check
    # E ModuleNotFoundError: No module named 'vermin'
    - pytest -vv --ignore=tests/test_py_info_collect.py
  requires:
    - pip
    - coverage >=7.5.4
    - pytest >=8.3.5
    - pytest-mock >=3.14
    - setuptools >=75.1

about:
  home: https://github.com/tox-dev/python-discovery
  summary: Python interpreter discovery
  description: |
    Python interpreter discovery locates Python interpreters installed on a system
    from various sources such as system packages, pyenv, mise, asdf, uv, or the
    Windows registry.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://python-discovery.readthedocs.io
  dev_url: https://github.com/tox-dev/python-discovery

extra:
  recipe-maintainers:
    - AnacondaRecipes/recipe-maintainers
  skip-lints:
    - avoid_noarch
